import { CoreModelInterface } from '../types/model-types';

export const coreModel: CoreModelInterface = {
  root: {
    apiType: 'none',
    preventedProperties: [
      'columns',
      'options',
      'serialize',
      'apiType',
      'layoutOnly',
      'value',
      'defaultValue',
      'emptyValue',
      'direction',
      'group',
      'layoutOnly',
    ],
    defaultProperties: ['type', 'name', 'title', 'items'],
    accepts: [
      'array',
      'boolean',
      'color',
      'date',
      'dateTime',
      'email',
      'grid',
      'group',
      'longtext',
      'month',
      'number',
      'object',
      'option',
      'options',
      'password',
      'radiogroup',
      'telephone',
      'text',
      'time',
      'week',
      'form',
    ],
  },
  array: {
    apiType: 'array',
    preventedProperties: [],
    defaultProperties: ['type', 'name', 'title', 'items'],
    accepts: [
      'array',
      'boolean',
      'color',
      'date',
      'dateTime',
      'email',
      'grid',
      'longtext',
      'month',
      'number',
      'object',
      'option',
      'options',
      'password',
      'radiogroup',
      'telephone',
      'text',
      'time',
      'week',
    ],
  },
  uiArray: {
    apiType: 'array',
    preventedProperties: ['items'],
    defaultProperties: ['type', 'name', 'title'],
    accepts: [],
  },
  boolean: {
    apiType: 'boolean',
    preventedProperties: [
      'items',
      'columns',
      'serializeDelimiter',
      'layoutOnly',
    ],
    defaultProperties: ['type', 'name', 'title'],
  },
  color: {
    apiType: 'string',
    preventedProperties: [
      'items',
      'columns',
      'serializeDelimiter',
      'layoutOnly',
    ],
    defaultProperties: ['type', 'name', 'title'],
  },
  date: {
    apiType: 'string',
    preventedProperties: [
      'items',
      'columns',
      'serializeDelimiter',
      'layoutOnly',
    ],
    defaultProperties: ['type', 'name', 'title'],
  },
  dateTime: {
    apiType: 'string',
    preventedProperties: [
      'items',
      'columns',
      'serializeDelimiter',
      'layoutOnly',
    ],
    defaultProperties: ['type', 'name', 'title'],
  },
  email: {
    apiType: 'string',
    preventedProperties: [
      'items',
      'columns',
      'serializeDelimiter',
      'layoutOnly',
    ],
    defaultProperties: ['type', 'name', 'title'],
  },
  grid: {
    apiType: 'none',
    preventedProperties: [
      'value',
      'defaultValue',
      'emptyValue',
      'serialize',
      'serializeDelimiter',
    ],
    defaultProperties: ['type', 'name', 'title', 'items', 'columns'],
    accepts: [
      'array',
      'boolean',
      'color',
      'date',
      'dateTime',
      'email',
      'grid',
      'group',
      'longtext',
      'month',
      'number',
      'object',
      'password',
      'radiogroup',
      'telephone',
      'text',
      'time',
      'week',
      'option',
      'options',
    ],
  },
  group: {
    apiType: 'none',
    preventedProperties: [
      'value',
      'defaultValue',
      'emptyValue',
      'serialize',
      'serializeDelimiter',
    ],
    defaultProperties: ['type', 'name', 'title', 'items'],
    accepts: [
      'array',
      'boolean',
      'color',
      'date',
      'dateTime',
      'email',
      'grid',
      'group',
      'longtext',
      'month',
      'number',
      'object',
      'password',
      'radiogroup',
      'telephone',
      'text',
      'time',
      'week',
      'options',
      'option',
    ],
  },
  month: {
    apiType: 'string',
    preventedProperties: [
      'items',
      'columns',
      'serializeDelimiter',
      'layoutOnly',
    ],
    defaultProperties: ['type', 'name', 'title'],
  },
  number: {
    apiType: 'number',
    preventedProperties: [
      'items',
      'columns',
      'serializeDelimiter',
      'layoutOnly',
    ],
    defaultProperties: ['type', 'name', 'title'],
  },
  uiObject: {
    apiType: 'object',
    preventedProperties: ['items'],
    defaultProperties: ['type', 'name', 'title'],
    accepts: [],
  },
  object: {
    apiType: 'object',
    preventedProperties: [],
    defaultProperties: ['type', 'name', 'title', 'items'],
    accepts: [
      'array',
      'boolean',
      'color',
      'date',
      'dateTime',
      'email',
      'grid',
      'group',
      'longtext',
      'month',
      'number',
      'object',
      'password',
      'radiogroup',
      'telephone',
      'text',
      'time',
      'week',
      'options',
      'option',
    ],
  },
  form: {
    apiType: 'object',
    preventedProperties: [],
    defaultProperties: ['type', 'name', 'title', 'items'],
    accepts: [
      'array',
      'boolean',
      'color',
      'date',
      'dateTime',
      'email',
      'grid',
      'group',
      'longtext',
      'month',
      'number',
      'object',
      'password',
      'radiogroup',
      'telephone',
      'text',
      'time',
      'week',
      'options',
      'option',
    ],
  },
  password: {
    apiType: 'string',
    preventedProperties: [
      'items',
      'columns',
      'layoutOnly',
      'serialize',
      'serializeDelimiter',
      'value',
      'defaultValue',
      'emptyValue',
    ],
    defaultProperties: ['type', 'name', 'title'],
  },
  radiogroup: {
    apiType: 'string',
    preventedProperties: [
      'items',
      'options',
      'serialize',
      'serializeDelimiter',
      'layoutOnly',
    ],
    defaultProperties: ['type', 'name', 'title', 'columns'],
    accepts: ['radioItem'],
  },
  radioItem: {
    apiType: 'none',
    preventedProperties: [
      'items',
      'columns',
      'layoutOnly',
      'serialize',
      'serializeDelimiter',
    ],
    defaultProperties: ['type', 'name', 'title'],
  },
  telephone: {
    apiType: 'string',
    preventedProperties: [
      'items',
      'columns',
      'layoutOnly',
      'serialize',
      'serializeDelimiter',
    ],
    defaultProperties: ['type', 'name', 'title'],
  },
  text: {
    apiType: 'string',
    preventedProperties: [
      'items',
      'columns',
      'layoutOnly',
      'serialize',
      'serializeDelimiter',
    ],
    defaultProperties: ['type', 'name', 'title'],
  },
  longtext: {
    apiType: 'string',
    preventedProperties: [
      'items',
      'layoutOnly',
      'serialize',
      'serializeDelimiter',
    ],
    defaultProperties: ['type', 'name', 'title'],
  },
  time: {
    apiType: 'string',
    preventedProperties: [
      'items',
      'columns',
      'layoutOnly',
      'serialize',
      'serializeDelimiter',
    ],
    defaultProperties: ['type', 'name', 'title'],
  },
  week: {
    apiType: 'string',
    preventedProperties: [
      'items',
      'columns',
      'layoutOnly',
      'serialize',
      'serializeDelimiter',
    ],
    defaultProperties: ['type', 'name', 'title'],
  },
  options: {
    apiType: 'array',
    preventedProperties: ['items', 'columns'],
    defaultProperties: [
      'items',
      'columns',
      'layoutOnly',
      'serialize',
      'serializeDelimiter',
    ],
  },
  option: {
    apiType: 'string',
    preventedProperties: ['items', 'columns'],
    defaultProperties: [
      'items',
      'columns',
      'layoutOnly',
      'serialize',
      'serializeDelimiter',
    ],
  },
};
