import {
  ApiModelType,
  CoreModelType,
  PropertyModelInterface,
} from '../typings/model-types';

export const propertiesModel: PropertyModelInterface = {
  name: {
    type: 'text',
    name: 'name',
    title: 'Name',
    defaultValue: '',
    hint: 'The unique identifier of this model.',
    readonly: false,
  },
  type: {
    type: 'option',
    name: 'type',
    title: 'Type',
    hint: 'The model type which defines the structure or format of this model.',
    defaultValue: 'text',
    readonly: false,
    options: [
      'array',
      'boolean',
      'color',
      'date',
      'dateTime',
      'email',
      'grid',
      'group',
      'longtext',
      'month',
      'number',
      'object',
      'password',
      'radiogroup',
      'radioItem',
      'root',
      'telephone',
      'text',
      'form',
      'options',
      'time',
      'week',
    ] as CoreModelType[],
  },
  apiType: {
    type: 'option',
    name: 'apiType',
    title: 'API Type',
    hint: 'The api model type which specifies how this model should interact with an API.',
    defaultValue: 'string',
    readonly: false,
    options: [
      'none',
      'array',
      'boolean',
      'number',
      'object',
      'string',
    ] as ApiModelType[],
  },
  title: {
    type: 'text',
    name: 'text',
    title: 'Title',
    defaultValue: '',
    hint: 'The title or label of the model.',
    readonly: false,
  },
  columns: {
    type: 'number',
    name: 'columns',
    title: 'Columns',
    defaultValue: [],
    hint: 'Specifies the number of columns in a layout.',
    readonly: false,
  },
  description: {
    type: 'longtext',
    name: 'description',
    title: 'Description',
    defaultValue: '',
    hint: 'A brief explanation of the model.',
    readonly: false,
  },
  hint: {
    type: 'text',
    name: 'hint',
    title: 'Hint',
    defaultValue: '',
    hint: 'A hint to guide user interaction with the model.',
    readonly: false,
  },
  group: {
    type: 'text',
    name: 'group',
    title: 'Group',
    defaultValue: '',
    hint: 'The group to which this model belongs.',
    readonly: false,
  },
  uiType: {
    type: 'text',
    name: 'uiType',
    title: 'UI Type',
    defaultValue: '',
    hint: 'Defines the User Interface type that should be used for this model.',
    readonly: false,
  },
  icon: {
    type: 'text',
    name: 'icon',
    title: 'Icon',
    defaultValue: '',
    hint: 'Icon associated with the model.',
    readonly: false,
  },
  size: {
    type: 'text',
    name: 'size',
    title: 'Size',
    defaultValue: '',
    hint: 'Specifies the size of the model.',
    readonly: false,
  },
  hidden: {
    type: 'option',
    apiType: 'boolean',
    name: 'hidden',
    title: 'Hidden',
    defaultValue: false,
    hint: 'If set to true, the model will be hidden.',
    readonly: false,
    options: [true, false],
  },
  collapsed: {
    type: 'option',
    apiType: 'boolean',
    name: 'collapsed',
    title: 'Collapsed',
    defaultValue: false,
    hint: 'If set to true, the model will initially be displayed in a collapsed state.',
    readonly: false,
    options: [true, false],
  },
  fullWidth: {
    type: 'option',
    apiType: 'boolean',
    name: 'fullWidth',
    title: 'Full Width',
    defaultValue: false,
    hint: 'If set to true, the model will take up the full available width.',
    readonly: false,
    options: [true, false],
  },
  collapsible: {
    type: 'option',
    apiType: 'boolean',
    name: 'collapsible',
    title: 'Collapsible',
    defaultValue: false,
    hint: 'If set to true, the model will be support collapsed states.',
    readonly: false,
    options: [true, false],
  },
  inline: {
    type: 'option',
    apiType: 'boolean',
    name: 'inline',
    title: 'Inline',
    defaultValue: false,
    hint: 'If set to true, the model will be displayed inline with other elements.',
    readonly: false,
    options: [true, false],
  },
  nullable: {
    type: 'option',
    apiType: 'boolean',
    name: 'nullable',
    title: 'Nullable',
    defaultValue: false,
    hint: 'If set to true, the value can be null.',
    readonly: false,
    options: [true, false],
  },
  layoutOnly: {
    type: 'option',
    apiType: 'boolean',
    name: 'layoutOnly',
    title: 'Layout Only',
    defaultValue: false,
    hint: 'If set to true, this model does not show titles or other, only items and layout.',
    readonly: false,
    options: [true, false],
  },
  multiple: {
    type: 'option',
    apiType: 'boolean',
    name: 'multiple',
    title: 'Allow multiple',
    defaultValue: false,
    hint: 'If set to true, the model can choose from multiple option values.',
    readonly: false,
    options: [true, false],
  },
  readonly: {
    type: 'option',
    apiType: 'boolean',
    name: 'readonly',
    title: 'Readonly',
    defaultValue: false,
    hint: ' If set to true, the model will be read-only and cannot be changed.',
    readonly: false,
    options: [true, false],
  },
  serialize: {
    type: 'option',
    apiType: 'boolean',
    name: 'serialize',
    title: 'Serialize Value',
    defaultValue: false,
    hint: 'If set to true, the value will be turned into a string when stored.',
    readonly: false,
    options: [true, false],
  },
  serializeDelimiter: {
    type: 'text',
    name: 'serializeDelimiter',
    title: 'Serialize Delimiter',
    defaultValue: ',',
    hint: 'The delimiter used when serializing an array to a string.',
    readonly: false,
  },
  defaultValue: {
    type: 'text',
    inheritType: true,
    name: 'defaultValue',
    title: 'Default Value',
    hint: 'The default value of the model.',
    readonly: false,
  },
  emptyValue: {
    type: 'text',
    inheritType: true,
    name: 'emptyValue',
    title: 'Empty Value',
    hint: 'The value that represents an undefined value of the model.',
    readonly: false,
  },
  value: {
    type: 'text',
    inheritType: true,
    name: 'value',
    title: 'Value',
    hint: 'The current value of the model.',
    readonly: false,
  },
  initialValue: {
    type: 'text',
    inheritType: true,
    name: 'initialValue',
    title: 'Initial Value',
    hint: 'The initial value of the model when created',
    readonly: true,
  },
  items: {
    type: 'array',
    name: 'items',
    title: 'Items',
    defaultValue: [],
    hint: 'An array of sub-models.',
    readonly: true,
  },
  options: {
    type: 'array',
    name: 'options',
    title: 'Options',
    defaultValue: [],
    hint: 'An array of options available for this model.',
    readonly: false,
  },
  width: {
    type: 'text',
    name: 'width',
    title: 'Width',
    defaultValue: '',
    hint: 'The width of the model, typically a CSS width value like "100%" or "50px".',
    readonly: false,
  },
  direction: {
    type: 'option',
    name: 'direction',
    title: 'Direction',
    defaultValue: 'vertical',
    hint: 'The direction of the layout. The possible values are "horizontal" or "vertical".',
    options: ['vertical', 'horizontal'],
    readonly: false,
  },
};
